version: "3.8"

services:
  app:
    image: 899522950715.dkr.ecr.ap-southeast-1.amazonaws.com/it-taskhub:${IMAGE_TAG:-latest}
    container_name: it-taskhub
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://admin1234:rdpostgres@postgres.holmcloud.net:5433/it_taskhub
      - NEXTAUTH_URL=https://taskhub.holmcloud.net
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NODE_ENV=production
    volumes:
      - uploads:/app/uploads
    networks:
      - taskhub-net

volumes:
  uploads:
    driver: local

networks:
  taskhub-net:
    driver: bridge
